server:
  port: 8088

spring:
    datasource:
        name: test
        url: jdbc:mysql://47.100.211.121:3306/lilac
        username: root
        password: shanyao

mybatis:
  mapper-locations: classpath:com/love/mybatis*.xml
  type-aliases-package: classpath:com/love/domain

