server:
  port: 8001

spring:
    datasource:
        name: test
        url: jdbc:mysql://47.100.211.121:3306/lilac
        username: root
        password: Sy940801..
        # 使用druid数据源
#        driver-class-name: com.mysql.jdbc.Driver
